package com.alexan.findevents.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.alexan.findevents.dao.DBImage;
import com.alexan.findevents.dao.DBUser;
import com.alexan.findevents.dao.DBPerson;
import com.alexan.findevents.dao.DBCategory;
import com.alexan.findevents.dao.DBFavCategory;
import com.alexan.findevents.dao.DBFriend;
import com.alexan.findevents.dao.DBEvent;
import com.alexan.findevents.dao.DBEventCategory;
import com.alexan.findevents.dao.DBLocation;
import com.alexan.findevents.dao.DBProvince;
import com.alexan.findevents.dao.DBCity;
import com.alexan.findevents.dao.DBDistrict;
import com.alexan.findevents.dao.DBComment;
import com.alexan.findevents.dao.DBHotSpot;
import com.alexan.findevents.dao.DBHotEvent;
import com.alexan.findevents.dao.DBRTEvent;
import com.alexan.findevents.dao.DBCategoryEvent;
import com.alexan.findevents.dao.DBSearchResultEvent;
import com.alexan.findevents.dao.DBFriendEvent;
import com.alexan.findevents.dao.DBEventMessage;
import com.alexan.findevents.dao.DBFriendMessage;
import com.alexan.findevents.dao.DBTimeRecorder;

import com.alexan.findevents.dao.DBImageDao;
import com.alexan.findevents.dao.DBUserDao;
import com.alexan.findevents.dao.DBPersonDao;
import com.alexan.findevents.dao.DBCategoryDao;
import com.alexan.findevents.dao.DBFavCategoryDao;
import com.alexan.findevents.dao.DBFriendDao;
import com.alexan.findevents.dao.DBEventDao;
import com.alexan.findevents.dao.DBEventCategoryDao;
import com.alexan.findevents.dao.DBLocationDao;
import com.alexan.findevents.dao.DBProvinceDao;
import com.alexan.findevents.dao.DBCityDao;
import com.alexan.findevents.dao.DBDistrictDao;
import com.alexan.findevents.dao.DBCommentDao;
import com.alexan.findevents.dao.DBHotSpotDao;
import com.alexan.findevents.dao.DBHotEventDao;
import com.alexan.findevents.dao.DBRTEventDao;
import com.alexan.findevents.dao.DBCategoryEventDao;
import com.alexan.findevents.dao.DBSearchResultEventDao;
import com.alexan.findevents.dao.DBFriendEventDao;
import com.alexan.findevents.dao.DBEventMessageDao;
import com.alexan.findevents.dao.DBFriendMessageDao;
import com.alexan.findevents.dao.DBTimeRecorderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBImageDaoConfig;
    private final DaoConfig dBUserDaoConfig;
    private final DaoConfig dBPersonDaoConfig;
    private final DaoConfig dBCategoryDaoConfig;
    private final DaoConfig dBFavCategoryDaoConfig;
    private final DaoConfig dBFriendDaoConfig;
    private final DaoConfig dBEventDaoConfig;
    private final DaoConfig dBEventCategoryDaoConfig;
    private final DaoConfig dBLocationDaoConfig;
    private final DaoConfig dBProvinceDaoConfig;
    private final DaoConfig dBCityDaoConfig;
    private final DaoConfig dBDistrictDaoConfig;
    private final DaoConfig dBCommentDaoConfig;
    private final DaoConfig dBHotSpotDaoConfig;
    private final DaoConfig dBHotEventDaoConfig;
    private final DaoConfig dBRTEventDaoConfig;
    private final DaoConfig dBCategoryEventDaoConfig;
    private final DaoConfig dBSearchResultEventDaoConfig;
    private final DaoConfig dBFriendEventDaoConfig;
    private final DaoConfig dBEventMessageDaoConfig;
    private final DaoConfig dBFriendMessageDaoConfig;
    private final DaoConfig dBTimeRecorderDaoConfig;

    private final DBImageDao dBImageDao;
    private final DBUserDao dBUserDao;
    private final DBPersonDao dBPersonDao;
    private final DBCategoryDao dBCategoryDao;
    private final DBFavCategoryDao dBFavCategoryDao;
    private final DBFriendDao dBFriendDao;
    private final DBEventDao dBEventDao;
    private final DBEventCategoryDao dBEventCategoryDao;
    private final DBLocationDao dBLocationDao;
    private final DBProvinceDao dBProvinceDao;
    private final DBCityDao dBCityDao;
    private final DBDistrictDao dBDistrictDao;
    private final DBCommentDao dBCommentDao;
    private final DBHotSpotDao dBHotSpotDao;
    private final DBHotEventDao dBHotEventDao;
    private final DBRTEventDao dBRTEventDao;
    private final DBCategoryEventDao dBCategoryEventDao;
    private final DBSearchResultEventDao dBSearchResultEventDao;
    private final DBFriendEventDao dBFriendEventDao;
    private final DBEventMessageDao dBEventMessageDao;
    private final DBFriendMessageDao dBFriendMessageDao;
    private final DBTimeRecorderDao dBTimeRecorderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBImageDaoConfig = daoConfigMap.get(DBImageDao.class).clone();
        dBImageDaoConfig.initIdentityScope(type);

        dBUserDaoConfig = daoConfigMap.get(DBUserDao.class).clone();
        dBUserDaoConfig.initIdentityScope(type);

        dBPersonDaoConfig = daoConfigMap.get(DBPersonDao.class).clone();
        dBPersonDaoConfig.initIdentityScope(type);

        dBCategoryDaoConfig = daoConfigMap.get(DBCategoryDao.class).clone();
        dBCategoryDaoConfig.initIdentityScope(type);

        dBFavCategoryDaoConfig = daoConfigMap.get(DBFavCategoryDao.class).clone();
        dBFavCategoryDaoConfig.initIdentityScope(type);

        dBFriendDaoConfig = daoConfigMap.get(DBFriendDao.class).clone();
        dBFriendDaoConfig.initIdentityScope(type);

        dBEventDaoConfig = daoConfigMap.get(DBEventDao.class).clone();
        dBEventDaoConfig.initIdentityScope(type);

        dBEventCategoryDaoConfig = daoConfigMap.get(DBEventCategoryDao.class).clone();
        dBEventCategoryDaoConfig.initIdentityScope(type);

        dBLocationDaoConfig = daoConfigMap.get(DBLocationDao.class).clone();
        dBLocationDaoConfig.initIdentityScope(type);

        dBProvinceDaoConfig = daoConfigMap.get(DBProvinceDao.class).clone();
        dBProvinceDaoConfig.initIdentityScope(type);

        dBCityDaoConfig = daoConfigMap.get(DBCityDao.class).clone();
        dBCityDaoConfig.initIdentityScope(type);

        dBDistrictDaoConfig = daoConfigMap.get(DBDistrictDao.class).clone();
        dBDistrictDaoConfig.initIdentityScope(type);

        dBCommentDaoConfig = daoConfigMap.get(DBCommentDao.class).clone();
        dBCommentDaoConfig.initIdentityScope(type);

        dBHotSpotDaoConfig = daoConfigMap.get(DBHotSpotDao.class).clone();
        dBHotSpotDaoConfig.initIdentityScope(type);

        dBHotEventDaoConfig = daoConfigMap.get(DBHotEventDao.class).clone();
        dBHotEventDaoConfig.initIdentityScope(type);

        dBRTEventDaoConfig = daoConfigMap.get(DBRTEventDao.class).clone();
        dBRTEventDaoConfig.initIdentityScope(type);

        dBCategoryEventDaoConfig = daoConfigMap.get(DBCategoryEventDao.class).clone();
        dBCategoryEventDaoConfig.initIdentityScope(type);

        dBSearchResultEventDaoConfig = daoConfigMap.get(DBSearchResultEventDao.class).clone();
        dBSearchResultEventDaoConfig.initIdentityScope(type);

        dBFriendEventDaoConfig = daoConfigMap.get(DBFriendEventDao.class).clone();
        dBFriendEventDaoConfig.initIdentityScope(type);

        dBEventMessageDaoConfig = daoConfigMap.get(DBEventMessageDao.class).clone();
        dBEventMessageDaoConfig.initIdentityScope(type);

        dBFriendMessageDaoConfig = daoConfigMap.get(DBFriendMessageDao.class).clone();
        dBFriendMessageDaoConfig.initIdentityScope(type);

        dBTimeRecorderDaoConfig = daoConfigMap.get(DBTimeRecorderDao.class).clone();
        dBTimeRecorderDaoConfig.initIdentityScope(type);

        dBImageDao = new DBImageDao(dBImageDaoConfig, this);
        dBUserDao = new DBUserDao(dBUserDaoConfig, this);
        dBPersonDao = new DBPersonDao(dBPersonDaoConfig, this);
        dBCategoryDao = new DBCategoryDao(dBCategoryDaoConfig, this);
        dBFavCategoryDao = new DBFavCategoryDao(dBFavCategoryDaoConfig, this);
        dBFriendDao = new DBFriendDao(dBFriendDaoConfig, this);
        dBEventDao = new DBEventDao(dBEventDaoConfig, this);
        dBEventCategoryDao = new DBEventCategoryDao(dBEventCategoryDaoConfig, this);
        dBLocationDao = new DBLocationDao(dBLocationDaoConfig, this);
        dBProvinceDao = new DBProvinceDao(dBProvinceDaoConfig, this);
        dBCityDao = new DBCityDao(dBCityDaoConfig, this);
        dBDistrictDao = new DBDistrictDao(dBDistrictDaoConfig, this);
        dBCommentDao = new DBCommentDao(dBCommentDaoConfig, this);
        dBHotSpotDao = new DBHotSpotDao(dBHotSpotDaoConfig, this);
        dBHotEventDao = new DBHotEventDao(dBHotEventDaoConfig, this);
        dBRTEventDao = new DBRTEventDao(dBRTEventDaoConfig, this);
        dBCategoryEventDao = new DBCategoryEventDao(dBCategoryEventDaoConfig, this);
        dBSearchResultEventDao = new DBSearchResultEventDao(dBSearchResultEventDaoConfig, this);
        dBFriendEventDao = new DBFriendEventDao(dBFriendEventDaoConfig, this);
        dBEventMessageDao = new DBEventMessageDao(dBEventMessageDaoConfig, this);
        dBFriendMessageDao = new DBFriendMessageDao(dBFriendMessageDaoConfig, this);
        dBTimeRecorderDao = new DBTimeRecorderDao(dBTimeRecorderDaoConfig, this);

        registerDao(DBImage.class, dBImageDao);
        registerDao(DBUser.class, dBUserDao);
        registerDao(DBPerson.class, dBPersonDao);
        registerDao(DBCategory.class, dBCategoryDao);
        registerDao(DBFavCategory.class, dBFavCategoryDao);
        registerDao(DBFriend.class, dBFriendDao);
        registerDao(DBEvent.class, dBEventDao);
        registerDao(DBEventCategory.class, dBEventCategoryDao);
        registerDao(DBLocation.class, dBLocationDao);
        registerDao(DBProvince.class, dBProvinceDao);
        registerDao(DBCity.class, dBCityDao);
        registerDao(DBDistrict.class, dBDistrictDao);
        registerDao(DBComment.class, dBCommentDao);
        registerDao(DBHotSpot.class, dBHotSpotDao);
        registerDao(DBHotEvent.class, dBHotEventDao);
        registerDao(DBRTEvent.class, dBRTEventDao);
        registerDao(DBCategoryEvent.class, dBCategoryEventDao);
        registerDao(DBSearchResultEvent.class, dBSearchResultEventDao);
        registerDao(DBFriendEvent.class, dBFriendEventDao);
        registerDao(DBEventMessage.class, dBEventMessageDao);
        registerDao(DBFriendMessage.class, dBFriendMessageDao);
        registerDao(DBTimeRecorder.class, dBTimeRecorderDao);
    }
    
    public void clear() {
        dBImageDaoConfig.getIdentityScope().clear();
        dBUserDaoConfig.getIdentityScope().clear();
        dBPersonDaoConfig.getIdentityScope().clear();
        dBCategoryDaoConfig.getIdentityScope().clear();
        dBFavCategoryDaoConfig.getIdentityScope().clear();
        dBFriendDaoConfig.getIdentityScope().clear();
        dBEventDaoConfig.getIdentityScope().clear();
        dBEventCategoryDaoConfig.getIdentityScope().clear();
        dBLocationDaoConfig.getIdentityScope().clear();
        dBProvinceDaoConfig.getIdentityScope().clear();
        dBCityDaoConfig.getIdentityScope().clear();
        dBDistrictDaoConfig.getIdentityScope().clear();
        dBCommentDaoConfig.getIdentityScope().clear();
        dBHotSpotDaoConfig.getIdentityScope().clear();
        dBHotEventDaoConfig.getIdentityScope().clear();
        dBRTEventDaoConfig.getIdentityScope().clear();
        dBCategoryEventDaoConfig.getIdentityScope().clear();
        dBSearchResultEventDaoConfig.getIdentityScope().clear();
        dBFriendEventDaoConfig.getIdentityScope().clear();
        dBEventMessageDaoConfig.getIdentityScope().clear();
        dBFriendMessageDaoConfig.getIdentityScope().clear();
        dBTimeRecorderDaoConfig.getIdentityScope().clear();
    }

    public DBImageDao getDBImageDao() {
        return dBImageDao;
    }

    public DBUserDao getDBUserDao() {
        return dBUserDao;
    }

    public DBPersonDao getDBPersonDao() {
        return dBPersonDao;
    }

    public DBCategoryDao getDBCategoryDao() {
        return dBCategoryDao;
    }

    public DBFavCategoryDao getDBFavCategoryDao() {
        return dBFavCategoryDao;
    }

    public DBFriendDao getDBFriendDao() {
        return dBFriendDao;
    }

    public DBEventDao getDBEventDao() {
        return dBEventDao;
    }

    public DBEventCategoryDao getDBEventCategoryDao() {
        return dBEventCategoryDao;
    }

    public DBLocationDao getDBLocationDao() {
        return dBLocationDao;
    }

    public DBProvinceDao getDBProvinceDao() {
        return dBProvinceDao;
    }

    public DBCityDao getDBCityDao() {
        return dBCityDao;
    }

    public DBDistrictDao getDBDistrictDao() {
        return dBDistrictDao;
    }

    public DBCommentDao getDBCommentDao() {
        return dBCommentDao;
    }

    public DBHotSpotDao getDBHotSpotDao() {
        return dBHotSpotDao;
    }

    public DBHotEventDao getDBHotEventDao() {
        return dBHotEventDao;
    }

    public DBRTEventDao getDBRTEventDao() {
        return dBRTEventDao;
    }

    public DBCategoryEventDao getDBCategoryEventDao() {
        return dBCategoryEventDao;
    }

    public DBSearchResultEventDao getDBSearchResultEventDao() {
        return dBSearchResultEventDao;
    }

    public DBFriendEventDao getDBFriendEventDao() {
        return dBFriendEventDao;
    }

    public DBEventMessageDao getDBEventMessageDao() {
        return dBEventMessageDao;
    }

    public DBFriendMessageDao getDBFriendMessageDao() {
        return dBFriendMessageDao;
    }

    public DBTimeRecorderDao getDBTimeRecorderDao() {
        return dBTimeRecorderDao;
    }

}
