package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBCOMMENT.
 */
public class DBComment {

    private Long id;
    private Long eventID;
    private Long userID;
    private String username;
    private Long targetUserID;
    private Long targetCommentID;
    private String comentContent;
    private Integer commentType;
    private Integer visibleScope;
    private Long timestamp;

    public DBComment() {
    }

    public DBComment(Long id) {
        this.id = id;
    }

    public DBComment(Long id, Long eventID, Long userID, String username, Long targetUserID, Long targetCommentID, String comentContent, Integer commentType, Integer visibleScope, Long timestamp) {
        this.id = id;
        this.eventID = eventID;
        this.userID = userID;
        this.username = username;
        this.targetUserID = targetUserID;
        this.targetCommentID = targetCommentID;
        this.comentContent = comentContent;
        this.commentType = commentType;
        this.visibleScope = visibleScope;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventID() {
        return eventID;
    }

    public void setEventID(Long eventID) {
        this.eventID = eventID;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Long getTargetUserID() {
        return targetUserID;
    }

    public void setTargetUserID(Long targetUserID) {
        this.targetUserID = targetUserID;
    }

    public Long getTargetCommentID() {
        return targetCommentID;
    }

    public void setTargetCommentID(Long targetCommentID) {
        this.targetCommentID = targetCommentID;
    }

    public String getComentContent() {
        return comentContent;
    }

    public void setComentContent(String comentContent) {
        this.comentContent = comentContent;
    }

    public Integer getCommentType() {
        return commentType;
    }

    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    public Integer getVisibleScope() {
        return visibleScope;
    }

    public void setVisibleScope(Integer visibleScope) {
        this.visibleScope = visibleScope;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
