package com.alexan.findevents.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.alexan.findevents.dao.DBFavCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DBFAV_CATEGORY.
*/
public class DBFavCategoryDao extends AbstractDao<DBFavCategory, Long> {

    public static final String TABLENAME = "DBFAV_CATEGORY";

    /**
     * Properties of entity DBFavCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PersonID = new Property(1, Long.class, "personID", false, "PERSON_ID");
        public final static Property CategoryID = new Property(2, Long.class, "categoryID", false, "CATEGORY_ID");
        public final static Property Timestamp = new Property(3, Long.class, "timestamp", false, "TIMESTAMP");
    };


    public DBFavCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public DBFavCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DBFAV_CATEGORY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PERSON_ID' INTEGER," + // 1: personID
                "'CATEGORY_ID' INTEGER," + // 2: categoryID
                "'TIMESTAMP' INTEGER);"); // 3: timestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DBFAV_CATEGORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBFavCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long personID = entity.getPersonID();
        if (personID != null) {
            stmt.bindLong(2, personID);
        }
 
        Long categoryID = entity.getCategoryID();
        if (categoryID != null) {
            stmt.bindLong(3, categoryID);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(4, timestamp);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBFavCategory readEntity(Cursor cursor, int offset) {
        DBFavCategory entity = new DBFavCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // personID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // categoryID
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // timestamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBFavCategory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPersonID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCategoryID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTimestamp(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBFavCategory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBFavCategory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
