package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBFAV_CATEGORY.
 */
public class DBFavCategory {

    private Long id;
    private Long personID;
    private Long categoryID;
    private Long timestamp;

    public DBFavCategory() {
    }

    public DBFavCategory(Long id) {
        this.id = id;
    }

    public DBFavCategory(Long id, Long personID, Long categoryID, Long timestamp) {
        this.id = id;
        this.personID = personID;
        this.categoryID = categoryID;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPersonID() {
        return personID;
    }

    public void setPersonID(Long personID) {
        this.personID = personID;
    }

    public Long getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(Long categoryID) {
        this.categoryID = categoryID;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
