package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBFRIEND_MESSAGE.
 */
public class DBFriendMessage {

    private Long id;
    private Long friendID;
    private Long timestamp;

    public DBFriendMessage() {
    }

    public DBFriendMessage(Long id) {
        this.id = id;
    }

    public DBFriendMessage(Long id, Long friendID, Long timestamp) {
        this.id = id;
        this.friendID = friendID;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFriendID() {
        return friendID;
    }

    public void setFriendID(Long friendID) {
        this.friendID = friendID;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
