package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBFRIEND_EVENT.
 */
public class DBFriendEvent {

    private Long id;
    private Long eventID;
    private Long commentID;
    private Long timestamp;

    public DBFriendEvent() {
    }

    public DBFriendEvent(Long id) {
        this.id = id;
    }

    public DBFriendEvent(Long id, Long eventID, Long commentID, Long timestamp) {
        this.id = id;
        this.eventID = eventID;
        this.commentID = commentID;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventID() {
        return eventID;
    }

    public void setEventID(Long eventID) {
        this.eventID = eventID;
    }

    public Long getCommentID() {
        return commentID;
    }

    public void setCommentID(Long commentID) {
        this.commentID = commentID;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
