package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBIMAGE.
 */
public class DBImage {

    private Long id;
    private String imageUrl;
    private Integer cacheLevel;
    private Long referBigImageID;
    private Long timestamp;
    private Long eventID;
    private Long personID;

    public DBImage() {
    }

    public DBImage(Long id) {
        this.id = id;
    }

    public DBImage(Long id, String imageUrl, Integer cacheLevel, Long referBigImageID, Long timestamp, Long eventID, Long personID) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.cacheLevel = cacheLevel;
        this.referBigImageID = referBigImageID;
        this.timestamp = timestamp;
        this.eventID = eventID;
        this.personID = personID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Integer getCacheLevel() {
        return cacheLevel;
    }

    public void setCacheLevel(Integer cacheLevel) {
        this.cacheLevel = cacheLevel;
    }

    public Long getReferBigImageID() {
        return referBigImageID;
    }

    public void setReferBigImageID(Long referBigImageID) {
        this.referBigImageID = referBigImageID;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Long getEventID() {
        return eventID;
    }

    public void setEventID(Long eventID) {
        this.eventID = eventID;
    }

    public Long getPersonID() {
        return personID;
    }

    public void setPersonID(Long personID) {
        this.personID = personID;
    }

}
