package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBLOCATION.
 */
public class DBLocation {

    private Long id;
    private String addrName;
    private String addrDetail;
    private String addrCity;
    private String addrDistrict;
    private Long timestamp;

    public DBLocation() {
    }

    public DBLocation(Long id) {
        this.id = id;
    }

    public DBLocation(Long id, String addrName, String addrDetail, String addrCity, String addrDistrict, Long timestamp) {
        this.id = id;
        this.addrName = addrName;
        this.addrDetail = addrDetail;
        this.addrCity = addrCity;
        this.addrDistrict = addrDistrict;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddrName() {
        return addrName;
    }

    public void setAddrName(String addrName) {
        this.addrName = addrName;
    }

    public String getAddrDetail() {
        return addrDetail;
    }

    public void setAddrDetail(String addrDetail) {
        this.addrDetail = addrDetail;
    }

    public String getAddrCity() {
        return addrCity;
    }

    public void setAddrCity(String addrCity) {
        this.addrCity = addrCity;
    }

    public String getAddrDistrict() {
        return addrDistrict;
    }

    public void setAddrDistrict(String addrDistrict) {
        this.addrDistrict = addrDistrict;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
