package com.alexan.findevents.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBTIME_RECORDER.
 */
public class DBTimeRecorder {

    private Long id;
    private String tableName;
    private Long lastModifyTime;

    public DBTimeRecorder() {
    }

    public DBTimeRecorder(Long id) {
        this.id = id;
    }

    public DBTimeRecorder(Long id, String tableName, Long lastModifyTime) {
        this.id = id;
        this.tableName = tableName;
        this.lastModifyTime = lastModifyTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

}
